apiVersion: v1
kind: Secret
metadata: # kpt-merge: gitea/git-user-secret
  name: git-user-secret
  namespace: gitea
  annotations:
    internal.kpt.dev/upstream-identifier: '|Secret|gitea|git-user-secret'
type: kubernetes.io/basic-auth
stringData:
  username: gitea
  password: secret
