apiVersion: v1
kind: Namespace
metadata:
  name: openshift-storage
  labels:
    pod-security.kubernetes.io/warn: "privileged"
    pod-security.kubernetes.io/audit: "privileged"
    pod-security.kubernetes.io/enforce: "privileged"
  annotations:
    workload.openshift.io/allowed: management